### PR TITLE
Various Helix fixes.

### PR DESCRIPTION
**Pull request by anaconda**
Hey - here are the changes I've mentioned on the forum rebased on top of current master.

Although I believe commits are self explanatory, details can be found here: https://github.com/Fneufneu/skin.amber/pull/1#issue-49856091
(please note that some of the changes mentioned there are not applied here as you've fixed them already).

### CODE REVIEW

**Comment by pecinko** [comment]
Please explain those height fixes and MyVideoPlaylist animation problem.

**Comment by pecinko** [comment]
OK, I have included all but those height alterations.

**Comment by anaconda** [comment]
Height changes in Dialog*? You can see the third line is cut in half if it contains e.g. a "g" or "q" and needs to scroll. However, I have just retested these height changes and I can see that they're not enough: they need a +10 - e.g. https://github.com/anaconda/skin.amber/commit/213f566ca2f4b43fcc2a2c581dec99b62497ea6e needs to be 110, not 100. The same applies to other height changes too.

MyVideoPlaylist: when closed, on a Raspberry Pi, I can see a black screen for less then a seconds (I'd say ~400-500 ms). I think it's reloading the background or something like that and I'm not sure what causes that behavior. By switching the animation to DialogOpenClose it's less noticeable though (i.e. the black screen looks as if it is the animation).

**Comment by pecinko** [comment]
MyVideoPlaylist - did you test latest code? I've made some changes today.

**Comment by anaconda** [comment]
> MyVideoPlaylist - did you test latest code? I've made some changes today.
Aah, missed it! Yeah, problem disappeared :-)

**Comment by pecinko** [comment]
Back to a height problem - with height=99, 3 lines of text fits nicely on my end. /e.g. DialogOK

**Comment by pecinko** [comment]
screen shot 2015-01-04 at 17 03 21

**Comment by anaconda** [comment]
Hm I should've given more details. I get the same result when font is "(1/4) Default", when font instead is "(2/4) Default - no caps" you get this: http://i.imgur.com/bg4qjrG.png

**Comment by pecinko** [comment]
Should be good now.

**Comment by anaconda** [comment]
Confirmed - thanks.

**Pull request closed without merging**
